Add support for `RS256`, `COSEAlgorithmIdentifier -257`
veraison/go-cose pull request #140
Opened 2023-04-04 13:31 UTC by hslatman

This PR adds support for RSASSA PKCS #1 v1.5 signing and verification. I started with just `RS256`, but I can add the others too if this PR will be considered to be merged at some point.

Let me know if you want the tests to be more like a table; currently they're more like multiple copies.

I noticed that registering an algorithm was removed with https://github.com/veraison/go-cose/pull/101, but I could use the `RS256` (and potentially others) for some things. Adding in the `RS256` in all required places seemed to be the way to go, or will `RegisterAlgorithm` be reconsidered?

2023-04-04 14:43 UTC, thomas-fossati commented
Hi @hslatman, thanks very much for initiating the contribution, much appreciated!

As you probably know already RS256 is not amongst the recommended algorithms for COSE -- and for pretty good reasons :-)

So, it'd be good if you could file an associated issue where you describe the use case and where we can have a conversation on requirements, caveats, etc.

cheers!

2023-04-04 15:07 UTC, hslatman commented
Thank you, @thomas-fossati,

I've opened an issue: https://github.com/veraison/go-cose/issues/141.

For my use case, having just the `AlgorithmRS256` as a constant is probably fine. There's still a way to use RSASSA PKCS#1 v1.5 with the external `Signer` and `Verifier` approach, so that could be used if one needs it. The actual implementation could also be in a separate package, providing broader/legacy/interoperability cipher support, thus keeping the core `go-cose` package small and clean.

2023-04-04 21:39 UTC, thomas-fossati commented
> Thank you, @thomas-fossati,
> 
> I've opened an issue: #141.

Fantastic, thanks!  I'm on holiday until the 11th, so I can't join the discussion until then.

@SteveLasker @qmuntal @shizhMSFT @roywill @yogeshbdeshpande could you please chime in so we don't let Herman wait too long?  TIA

2023-06-30 15:50 UTC, yogeshbdeshpande commented
@hslatman Request please create a new PR fr adding the RS256 constant

2023-07-14 15:43 UTC, OR13 commented on algorithm.go
> +	AlgorithmRS256 Algorithm = -257
consider a link / comment to webauthn: https://www.w3.org/TR/webauthn-2/#sctn-sample-registration

2023-07-14 15:44 UTC, OR13 approved these changes

2023-07-14 15:44 UTC, OR13 commented on rsa.go
> +		if err := rsa.VerifyPKCS1v15(rv.key, hash, digest, signature); err != nil {
maybe you want to remove this part

2023-07-14 15:44 UTC, OR13 commented on rsa_test.go
> +	algRS256 := AlgorithmRS256
maybe you want to remove this part

2023-07-14 15:46 UTC, SteveLasker commented
Thanks, @hslatman for the PR and discussion #141 
After discussion with the maintainers, we'd like to keep the constant and remove the additional code. 
Much appreciated for your engagement.

2023-07-14 15:46 UTC, OR13 requested changes
seems like folks are requesting the constant be kept buy APIs on it throw some error related to it not being supported, without using an external signer

2023-08-11 15:50 UTC, roywill commented
We are not going to implement this algorithms but allowed the constant to be added in another pull request

2023-08-11 15:50 UTC, closed without merging