Upgrade fxamacker/cbor to v2.5.0
veraison/go-cose pull request #166
Opened 2023-08-18 10:19 UTC by qmuntal

`fxamacker/cbor` release notes: https://github.com/fxamacker/cbor/releases/tag/v2.5.0.

Fixes #165

2023-08-18 18:22 UTC, OR13 approved these changes

2023-08-21 19:14 UTC, OR13 approved these changes

2023-08-25 15:22 UTC, OR13 requested changes
On the call today, there was discussion on wanting "some number of additional unit tests" related to marshal and unmarshal.

This is vague, so any number of increases in unit tests would unblock my review.

I am requesting "additional unit tests" at the discretion of the maintainers.

2023-09-26 07:03 UTC, qmuntal commented
> @qmuntal to evaluate what additional tests are required to build confidence to merge.

I've gone through the test suite of other COSE libraries, most notably https://github.com/google/coset, and I haven't found any outstanding missing case on our suite. IMO this is ready to merge.

2023-09-26 13:12 UTC, OR13 approved these changes

2023-09-26 14:22 UTC, thomas-fossati approved these changes

2023-09-26 14:30 UTC, merged

2023-09-26 15:33 UTC, SteveLasker commented
Thanks, @qmuntal