Update Current Release & Pre-release Info
veraison/go-cose pull request #191
Opened 2024-07-18 17:29 UTC by SteveLasker

2024-07-18 18:17 UTC, SteveLasker commented
blocked on #192

2024-07-19 13:00 UTC, OR13 commented
Merge https://github.com/veraison/go-cose/pull/193 first

2024-07-19 13:02 UTC, OR13 commented on README.md
> +**Current Pre-Release**: [go-cose v1.2.0-alpha.1][current-pre-release]
```suggestion
**Current Pre-Release**: [go-cose v1.3.0-alpha.1][current-pre-release]
```

2024-07-19 13:02 UTC, OR13 commented on README.md
> +[current-pre-release]:  https://github.com/veraison/go-cose/releases/tag/v1.2.0-alpha.1
```suggestion
[current-pre-release]:  https://github.com/veraison/go-cose/releases/tag/v1.3.0-alpha.1
```

2024-07-19 13:02 UTC, OR13 requested changes
See comments on https://github.com/veraison/go-cose/issues/190

2024-07-19 15:06 UTC, OR13 approved these changes

2024-07-19 15:21 UTC, OR13 approved these changes

2024-07-19 16:40 UTC, merged